services:

  postgres:
    image: postgres:16

    container_name: moex-postgres

    environment:
      POSTGRES_DB: moex_dashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .

    container_name: moex-dashboard

    depends_on:
      - postgres

    env_file:
      - .env

    ports:
      - "8050:8050"

volumes:
  postgres_data: